name: deep-diff
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.12
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - colorama=0.4.6
  - contourpy=1.3.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - double-conversion=3.3.0
  - expat=2.6.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - freetype=2.12.1
  - graphite2=1.3.13
  - harfbuzz=9.0.0
  - icu=75.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.2
  - libclang13=19.1.2
  - libcups=2.3.3
  - libdeflate=1.22
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.2
  - libnsl=2.0.1
  - libntlm=1.4
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.0
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nomkl=1.0
  - numexpr=2.10.1
  - openjpeg=2.5.2
  - openldap=2.6.8
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - pcre2=10.44
  - pip=24.3.1
  - pixman=0.43.2
  - pthread-stubs=0.4
  - pyparsing=3.2.0
  - pyside6=6.8.0
  - python=3.10.15
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytz=2024.2
  - qhull=2020.2
  - qt6-main=6.8.0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.6
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wayland=1.23.1
  - wheel=0.44.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.2
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - filelock==3.13.1
      - fsspec==2024.2.0
      - idna==3.4
      - importlib-resources==6.4.5
      - jinja2==3.1.3
      - kornia==0.7.3
      - kornia-rs==0.1.7
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - nibabel==5.3.2
      - numpy==1.26.3
      - pillow==10.2.0
      - requests==2.28.1
      - scipy==1.14.1
      - surfa==0.6.1
      - sympy==1.13.1
      - torch==2.1.2+cu121
      - torchaudio==2.1.2+cu121
      - torchvision==0.16.2+cu121
      - triton==2.1.0
      - typing-extensions==4.9.0
      - urllib3==1.26.13
      - xxhash==3.5.0
